### ISSUE TITLE
Implement way to override underage actions

### ISSUE THREAD

**Issue by alexstandiford** [alexstandiford/easy-age-verifier#91]
Please work from the `2.05` branch, not `master` as that is the current working copy, and `master` is what's currently released.

https://wordpress.org/support/topic/is-it-posible-to-remove-underage-message/#post-9089455

**Comment by LiamBailey** [comment]
I can take this issue if it is still needed/open @alexstandiford ?

**Comment by alexstandiford** [comment]
Sure, go for it.

**Comment by alexstandiford** [comment]
@LiamBailey - Please branch off of `2.04` if possible!

**Comment by LiamBailey** [comment]
I will pull in the latest code sure, however it was my plan to work on my fork:master and then submit pull request from there rather than working on a branch?

**Comment by LiamBailey** [comment]
Oh - I see what you mean - no problem @alexstandiford

**Comment by alexstandiford** [comment]
Thanks @LiamBailey - I'm still a little green with managing a repo like this with the public (most of the updates to-date have been done by me, and me alone), so I wasn't as organized about where submitted code should go. Anyway, thanks again!

**Comment by LiamBailey** [comment]
Sorry which branch do you mean exactly @alexstandiford dev/2.0.4?

**Comment by LiamBailey** [comment]
https://github.com/alexstandiford/easy-age-verifier/tree/dev/2.04 ?

**Comment by LiamBailey** [comment]
I see the current version in master is 2.0.4 and your most recent commits are on https://github.com/alexstandiford/easy-age-verifier/commits/2.05 - so I should work on that branch right @alexstandiford ?

**Comment by alexstandiford** [comment]
Oh geez, yes, you're right. This is what happens when I make decisions before coffee. Thanks for checking.
